### ISSUE TITLE
This line and the one below seem to be inconsistent

### ISSUE THREAD

**Issue by HuyQVu** [dawenl/glad_cal500#1]
https://github.com/dawenl/glad_cal500/blob/34d8456db7078ad879290e819249f090b50ed9ac/glad_em.py#L119

**Comment by dawenl** [comment]
What is inconsistent?

**Comment by HuyQVu** [comment]
I might be wrong but could you explain why `((1-Lj) * np.log(tmp) + Lj * np.log(1-tmp)) ` in Line 119 is the same as `(Lj * np.log(1-tmp) + (1-Lj) * np.log(tmp)) ` in Line 120.

Thanks

**Comment by dawenl** [comment]
It's been a while, but this looks to me is simply a weighted sum of the conditional log-likelihood from line 119 and 120 where the weights are simply the posterior for label is -1 and 1 (`self.EZ[0, j]` and `self.EZ[1, j]`, respectively). It should become clear if you write down the objective.

**Comment by HuyQVu** [comment]
Thanks, for the first one `self.EZ[0, j]`, I agree the weight equals: `(1-Lj) * np.log(tmp) + Lj * np.log(1-tmp))`. However, for the second one `self.EZ[1, j]`, I think the weight should be `(Lj * np.log(tmp) + (1-Lj) * np.log(1-tmp)`

**Comment by dawenl** [comment]
It's been too long for me to remember (this is not my paper after all). If you think it should be that way, you can fork the repo and change it locally.

**Comment by HuyQVu** [comment]
Thank you!
